# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
